### ISSUE TITLE
Better file structure in plots folder

### ISSUE THREAD

**Issue by tbekolay** [nengo/pytest-plt#2]
Currently, the plots folder created by pytest-plt is based on the test function's `nodeid`. So, if the `nodeid` is something like `nengo/tests/test_thing.py::test_simple_thing` you end up with a nested folder like

```
plots
└── nengo
    └── tests
        └── test_thing.py::test_simple_thing.pdf
```

We should simplify / flatten this, though first we should decide the best way to simplify / flatten this.

**Comment by drasmuss** [comment]
A 2b option might be to omit the prefix for any files in the `top_level/tests` folder, but include it for tests in sub-modules.  So e.g.
```
nengo
└── tests
    └── test_thing.py
└── networks
    └── tests
        └── test_thing.py
```
would result in plots named
``test_thing.py::test_simple_thing.pdf``
and
``networks.tests.test_thing.py::test_simple_thing.pdf``

**Comment by hunse** [comment]
Yeah, that's a good idea. Though maybe we could be more general and have a list of folder names that we drop. By default, this list would just include "tests" (and maybe "test" as well). Then you'd end up with `test_thing.py::test_simple_thing.pdf` and `networks.test_thing.py::test_simple_thing.pdf`.

Also, I think for most projects, it makes sense to exclude the top level folder, but there could be exceptions. Maybe we could have that be another config option.

**Comment by hunse** [comment]
Also, my numbers above weren't for different options, rather they were different aspects of my single-option proposal. I'll change them to bullet points instead so it's clearer.

**Comment by tbekolay** [comment]
> We exclude everything before the final slash in `nodeid` by default.

I'm not a big fan of this just because there can be name collisions; the nodeid is unique, but not if you get rid of those earlier parts. At the same time, collisions are probably rare, but I think it'd be a lot of fiddly code to detect collisions. I like replacing `/` with `.` and having them all in one folder though, that seems like a good default especially if we can think of some ways to configure it to be shorter.

It occurs to me that if you have the directory full of plots, you could look at all of the filenames and find if they all have a common prefix (e.g. `nengo.tests`) and remove it if so. That would help a fair bit and guarantee no collisions, though would mean that if someone sets a custom name with `plt.saveas = 'a'` then it'd all fall apart due to no common prefixes...

One thing we could do is have the user specify the prefix manually instead? So say something like `prefix_to_remove = nengo.tests` and then when saving the plot do something like

```
if plt.saveas.startswith(prefix_to_remove):
    plt.saveas = plt.saveas[len(prefix_to_remove):]
```

That way custom `plt.saveas` names wouldn't get removed, but others would. I think (?) it would guarantee no collision.

**Comment by tbekolay** [comment]
Done in #11.
