### ISSUE TITLE
Adjust dirname or filename based on parameters

### ISSUE THREAD

**Issue by jgosmann** [nengo/pytest-plt#20]
In Nengo SPA some tests are parametrized like this:
```python
def pytest_generate_tests(metafunc):
    if 'algebra' in metafunc.fixturenames:
        metafunc.parametrize('algebra', [a for a in TestConfig.algebras])
```
It would be nice if there were an official way to include the `algebra` argument (or any other argument in the general case) in the dirname or filename/path of the output file without setting `saveas` in every test that makes use of this. (If this is not included in the filename, plots will be overwritten.)

**Comment by tbekolay** [comment]
`pytest-plt` uses the `nodeid` of the test, which is guaranteed to be unique because pytest uses this internally to identify tests. So it won't be quite as verbose as our old plot names, but you shouldn't get any issues with plots being overwritten. Do tests generated this way not get assigned unique `nodeid`s?

**Comment by jgosmann** [comment]
True, files are not being overwritten. I was looking at files from tests that I assumed to be parametrized that way, but they actually weren't. In fact, at the moment that parametrization is not combined with plotting in any of the tests. However, if one combines the two, only `algebra0`, `algebra1`, ... appears in the filenames which is not that helpful.

So this isn't really that important for me at the moment, but could still be nice to have.

**Comment by tbekolay** [comment]
You get the `algebra0` and `algebra1` in the filenames, so doesn't this mean we already have it?

**Comment by jgosmann** [comment]
But I don't know what `algebra0` and `algebra1` are without looking up how `TestConfig.algebras` is defined.

**Comment by tbekolay** [comment]
What's the ideal situation for you? It uses the `__str__` of the algebra? I think that would get too long in a lot of cases, and it won't necessarily be unique. My opinion is that if you need to differentiate two plots and the filename alone isn't enough, you should include that information in a `plt.title` or legend or something else inside the plot. I don't think the plot's filename should be doing the heavy lifting there, especially when the test `nodeid` is already a well-defined and useful unique string.

**Comment by jgosmann** [comment]
I suppose using the plot title is fine.
